// ============================================================================
// MOCK DATA - TASK MANAGEMENT SYSTEM DATA
// ============================================================================

import { DraftTask, AssignedTask, User, FilterOption, TaskDetails } from './types';

// Draft tasks data
export const MOCK_DRAFT_TASKS: DraftTask[] = [
  {
    id: "draft-1",
    title: "Review Farm Reports",
    status: "draft",
    assignedToLabel: "Farm Manager (5)",
    createdAt: "2025-09-01T10:30:00.000Z",
    dueDate: "2025-10-15T23:59:59.000Z",
  },
  {
    id: "draft-2", 
    title: "Soil Testing Plan",
    status: "draft",
    assignedToLabel: "Farm Manager (3)",
    createdAt: "2025-09-02T14:20:00.000Z",
    dueDate: "2025-11-20T23:59:59.000Z",
  },
  {
    id: "draft-3",
    title: "Crop Disease Assessment", 
    status: "draft",
    assignedToLabel: "Kisani Didi (8)",
    createdAt: "2025-09-03T09:15:00.000Z",
    dueDate: "2025-10-30T23:59:59.000Z",
  },
  {
    id: "draft-4",
    title: "Irrigation System Setup",
    status: "draft", 
    assignedToLabel: "Farm Operator (1)",
    createdAt: "2025-09-04T16:30:00.000Z",
    dueDate: "2025-12-10T23:59:59.000Z",
  },
  {
    id: "draft-5",
    title: "Fertilizer Distribution Plan",
    status: "draft",
    assignedToLabel: "Kisani Didi (2)", 
    createdAt: "2025-09-05T11:45:00.000Z",
    dueDate: "2025-11-05T23:59:59.000Z",
  },
];

export const MOCK_ASSIGNED_TASKS: AssignedTask[] = [
  {
    id: "assigned-1",
    title: "Crop Disease Survey",
    status: "assigned", 
    assignedToLabel: "Kisani Didi (8)",
    assignedAt: "2025-09-03T12:00:00.000Z",
    dueDate: "2025-10-25T23:59:59.000Z",
    taskStatus: "completed",
  },
  {
    id: "assigned-2",
    title: "Water Management",
    status: "assigned",
    assignedToLabel: "Kisani Didi(20)",
    assignedAt: "2025-09-04T08:30:00.000Z",
    dueDate: "2025-10-25T23:59:59.000Z",
    taskStatus: "in-progress",
  },
  {
    id: "assigned-3",
    title: "Harvest Planning",
    status: "assigned",
    assignedToLabel: "Kisani Didi (8)",
    assignedAt: "2025-09-05T14:15:00.000Z",
    dueDate: "2025-10-25T23:59:59.000Z",
    taskStatus: "overdue",
  },
  {
    id: "assigned-4", 
    title: "Seed Quality Check",
    status: "assigned",
    assignedToLabel: "Farm Manager (5)",
    assignedAt: "2025-09-06T09:00:00.000Z",
    dueDate: "2025-11-30T23:59:59.000Z",
    taskStatus: "completed",
  },
  {
    id: "assigned-5", 
    title: "Irrigation System Maintenance",
    status: "assigned",
    assignedToLabel: "Farm Operator (4)",
    assignedAt: "2025-09-07T10:00:00.000Z",
    dueDate: "2025-12-15T23:59:59.000Z",
    taskStatus: "in-progress",
  },
];

export const MOCK_USER_OPTIONS: User[] = [
  // Farm Managers
  {
    id: 1,
    name: "John Doe",
    memberId: "FM001",
    userType: "farm-manager",
    stateId: "1",
    districtId: "1",
    mandalId: "1",
    location: "Karnataka, Bangalore, Mandya",
  },
  {
    id: 2,
    name: "Suresh Kumar",
    memberId: "FM002",
    userType: "farm-manager",
    stateId: "2",
    districtId: "2",
    mandalId: "2",
    location: "Maharashtra, Pune, Shivaji Nagar",
  },
  {
    id: 3,
    name: "Rajesh Patel",
    memberId: "FM003",
    userType: "farm-manager",
    stateId: "1",
    districtId: "1",
    mandalId: "1",
    location: "Karnataka, Bangalore, Mandya",
  },
  {
    id: 4,
    name: "Amit Singh",
    memberId: "FM004",
    userType: "farm-manager",
    stateId: "3",
    districtId: "3",
    mandalId: "3",
    location: "Tamil Nadu, Chennai, T Nagar",
  },
  {
    id: 5,
    name: "Vikash Sharma",
    memberId: "FM005",
    userType: "farm-manager",
    stateId: "2",
    districtId: "2",
    mandalId: "2",
    location: "Maharashtra, Pune, Shivaji Nagar",
  },
  {
    id: 6,
    name: "Ravi Kumar",
    memberId: "FM006",
    userType: "farm-manager",
    stateId: "1",
    districtId: "1",
    mandalId: "1",
    location: "Karnataka, Bangalore, Mandya",
  },
  {
    id: 7,
    name: "Manoj Gupta",
    memberId: "FM007",
    userType: "farm-manager",
    stateId: "3",
    districtId: "3",
    mandalId: "3",
    location: "Tamil Nadu, Chennai, T Nagar",
  },
  {
    id: 8,
    name: "Deepak Verma",
    memberId: "FM008",
    userType: "farm-manager",
    stateId: "2",
    districtId: "2",
    mandalId: "2",
    location: "Maharashtra, Pune, Shivaji Nagar",
  },

  // Kisani Didi
  {
    id: 9,
    name: "Priya Sharma",
    memberId: "KD001",
    userType: "kisani-didi",
    stateId: "1",
    districtId: "1",
    mandalId: "1",
    location: "Karnataka, Bangalore, Mandya",
  },
  {
    id: 10,
    name: "Sunita Devi",
    memberId: "KD002",
    userType: "kisani-didi",
    stateId: "2",
    districtId: "2",
    mandalId: "2",
    location: "Maharashtra, Pune, Shivaji Nagar",
  },
  {
    id: 11,
    name: "Kavita Singh",
    memberId: "KD003",
    userType: "kisani-didi",
    stateId: "1",
    districtId: "1",
    mandalId: "1",
    location: "Karnataka, Bangalore, Mandya",
  },
  {
    id: 12,
    name: "Meera Patel",
    memberId: "KD004",
    userType: "kisani-didi",
    stateId: "3",
    districtId: "3",
    mandalId: "3",
    location: "Tamil Nadu, Chennai, T Nagar",
  },
  {
    id: 13,
    name: "Asha Kumari",
    memberId: "KD005",
    userType: "kisani-didi",
    stateId: "2",
    districtId: "2",
    mandalId: "2",
    location: "Maharashtra, Pune, Shivaji Nagar",
  },
  {
    id: 14,
    name: "Rekha Gupta",
    memberId: "KD006",
    userType: "kisani-didi",
    stateId: "1",
    districtId: "1",
    mandalId: "1",
    location: "Karnataka, Bangalore, Mandya",
  },
  {
    id: 15,
    name: "Geeta Sharma",
    memberId: "KD007",
    userType: "kisani-didi",
    stateId: "3",
    districtId: "3",
    mandalId: "3",
    location: "Tamil Nadu, Chennai, T Nagar",
  },
  {
    id: 16,
    name: "Sita Devi",
    memberId: "KD008",
    userType: "kisani-didi",
    stateId: "2",
    districtId: "2",
    mandalId: "2",
    location: "Maharashtra, Pune, Shivaji Nagar",
  },
  {
    id: 17,
    name: "Radha Singh",
    memberId: "KD009",
    userType: "kisani-didi",
    stateId: "1",
    districtId: "1",
    mandalId: "1",
    location: "Karnataka, Bangalore, Mandya",
  },
  {
    id: 18,
    name: "Lakshmi Patel",
    memberId: "KD010",
    userType: "kisani-didi",
    stateId: "3",
    districtId: "3",
    mandalId: "3",
    location: "Tamil Nadu, Chennai, T Nagar",
  },
  {
    id: 19,
    name: "Saraswati Kumar",
    memberId: "KD011",
    userType: "kisani-didi",
    stateId: "2",
    districtId: "2",
    mandalId: "2",
    location: "Maharashtra, Pune, Shivaji Nagar",
  },
  {
    id: 20,
    name: "Durga Devi",
    memberId: "KD012",
    userType: "kisani-didi",
    stateId: "1",
    districtId: "1",
    mandalId: "1",
    location: "Karnataka, Bangalore, Mandya",
  },
  {
    id: 21,
    name: "Parvati Sharma",
    memberId: "KD013",
    userType: "kisani-didi",
    stateId: "3",
    districtId: "3",
    mandalId: "3",
    location: "Tamil Nadu, Chennai, T Nagar",
  },
  {
    id: 22,
    name: "Kamala Singh",
    memberId: "KD014",
    userType: "kisani-didi",
    stateId: "2",
    districtId: "2",
    mandalId: "2",
    location: "Maharashtra, Pune, Shivaji Nagar",
  },
  {
    id: 23,
    name: "Shanti Gupta",
    memberId: "KD015",
    userType: "kisani-didi",
    stateId: "1",
    districtId: "1",
    mandalId: "1",
    location: "Karnataka, Bangalore, Mandya",
  },
  {
    id: 24,
    name: "Urmila Patel",
    memberId: "KD016",
    userType: "kisani-didi",
    stateId: "3",
    districtId: "3",
    mandalId: "3",
    location: "Tamil Nadu, Chennai, T Nagar",
  },
  {
    id: 25,
    name: "Savita Devi",
    memberId: "KD017",
    userType: "kisani-didi",
    stateId: "2",
    districtId: "2",
    mandalId: "2",
    location: "Maharashtra, Pune, Shivaji Nagar",
  },
  {
    id: 26,
    name: "Pushpa Kumar",
    memberId: "KD018",
    userType: "kisani-didi",
    stateId: "1",
    districtId: "1",
    mandalId: "1",
    location: "Karnataka, Bangalore, Mandya",
  },
  {
    id: 27,
    name: "Usha Sharma",
    memberId: "KD019",
    userType: "kisani-didi",
    stateId: "3",
    districtId: "3",
    mandalId: "3",
    location: "Tamil Nadu, Chennai, T Nagar",
  },
  {
    id: 28,
    name: "Kiran Singh",
    memberId: "KD020",
    userType: "kisani-didi",
    stateId: "2",
    districtId: "2",
    mandalId: "2",
    location: "Maharashtra, Pune, Shivaji Nagar",
  },

  // Farm Operators
  {
    id: 29,
    name: "Ramesh Kumar",
    memberId: "FO001",
    userType: "operator",
    stateId: "1",
    districtId: "1",
    mandalId: "1",
    location: "Karnataka, Bangalore, Mandya",
  },
  {
    id: 30,
    name: "Sunil Yadav",
    memberId: "FO002",
    userType: "operator",
    stateId: "2",
    districtId: "2",
    mandalId: "2",
    location: "Maharashtra, Pune, Shivaji Nagar",
  },
  {
    id: 31,
    name: "Prakash Singh",
    memberId: "FO003",
    userType: "operator",
    stateId: "3",
    districtId: "3",
    mandalId: "3",
    location: "Tamil Nadu, Chennai, T Nagar",
  },
  {
    id: 32,
    name: "Mahesh Gupta",
    memberId: "FO004",
    userType: "operator",
    stateId: "1",
    districtId: "1",
    mandalId: "1",
    location: "Karnataka, Bangalore, Mandya",
  },
  {
    id: 33,
    name: "Dinesh Patel",
    memberId: "FO005",
    userType: "operator",
    stateId: "2",
    districtId: "2",
    mandalId: "2",
    location: "Maharashtra, Pune, Shivaji Nagar",
  },
  {
    id: 34,
    name: "Naresh Kumar",
    memberId: "FO006",
    userType: "operator",
    stateId: "3",
    districtId: "3",
    mandalId: "3",
    location: "Tamil Nadu, Chennai, T Nagar",
  },
  {
    id: 35,
    name: "Mukesh Sharma",
    memberId: "FO007",
    userType: "operator",
    stateId: "1",
    districtId: "1",
    mandalId: "1",
    location: "Karnataka, Bangalore, Mandya",
  },
  {
    id: 36,
    name: "Yogesh Singh",
    memberId: "FO008",
    userType: "operator",
    stateId: "2",
    districtId: "2",
    mandalId: "2",
    location: "Maharashtra, Pune, Shivaji Nagar",
  },
  {
    id: 37,
    name: "Lokesh Gupta",
    memberId: "FO009",
    userType: "operator",
    stateId: "3",
    districtId: "3",
    mandalId: "3",
    location: "Tamil Nadu, Chennai, T Nagar",
  },
  {
    id: 38,
    name: "Hitesh Patel",
    memberId: "FO010",
    userType: "operator",
    stateId: "1",
    districtId: "1",
    mandalId: "1",
    location: "Karnataka, Bangalore, Mandya",
  },
  {
    id: 39,
    name: "Jitesh Kumar",
    memberId: "FO011",
    userType: "operator",
    stateId: "2",
    districtId: "2",
    mandalId: "2",
    location: "Maharashtra, Pune, Shivaji Nagar",
  },
  {
    id: 40,
    name: "Nitesh Sharma",
    memberId: "FO012",
    userType: "operator",
    stateId: "3",
    districtId: "3",
    mandalId: "3",
    location: "Tamil Nadu, Chennai, T Nagar",
  },
];

// Filter options for dropdowns

export const MOCK_ASSIGNED_TO_OPTIONS: FilterOption[] = [
  { value: "", label: "All" },
  { value: "farm-manager", label: "Farm Manager" },
  { value: "kisani-didi", label: "Kisani Didi" },
  { value: "operator", label: "Farm Operator" },
];

// MOCK TASK DETAILS - REMOVE WHEN API IS DEPLOYED
export const MOCK_TASK_DETAILS: { [key: string]: TaskDetails } = {
  "draft-1": {
    id: "draft-1",
    title: "Review Farm Reports",
    description: "Review and approve farm reports for Q3 2025. Check yield data, soil conditions, and pest management reports.",
    status: "draft",
    assigneeUserType: "fm", // Farm Manager (collective)
    assigneeId: null,
    assignedAt: null,
    dueDate: "2025-09-15T00:00:00.000Z",
    createdAt: "2025-09-01T10:30:00.000Z",
    updatedAt: "2025-09-01T10:30:00.000Z",
    stateName: "Karnataka",
    districtName: "Bangalore",
    mandalName: "Mandya",
    assignedToLabel: "Farm Manager (5)",
    assignedCount: 5, // 5 farm managers will be assigned
  },
  "draft-2": {
    id: "draft-2",
    title: "Soil Testing Plan",
    description: "Draft a comprehensive plan for soil testing in the northern region. Include pH testing, nutrient analysis, and contamination checks.",
    status: "draft",
    assigneeUserType: "ifm", // Individual Farm Manager
    assigneeId: "user-2",
    assignedAt: null,
    dueDate: "2025-10-25T23:59:59.000Z",
    createdAt: "2025-09-02T14:20:00.000Z",
    updatedAt: "2025-09-02T14:20:00.000Z",
    stateName: "Karnataka",
    districtName: "Bangalore",
    mandalName: "Mandya",
    assignedToLabel: "Farm Manager (3)",
    assignedCount: 1, // 1 specific farm manager
  },
  "draft-3": {
    id: "draft-3",
    title: "Crop Disease Assessment",
    description: "Conduct thorough assessment of crop diseases affecting wheat and rice crops in the region.",
    status: "draft",
    assigneeUserType: "ikd", // Individual Kisani Didi
    assigneeId: "user-3",
    assignedAt: null,
    dueDate: "2025-11-30T23:59:59.000Z",
    createdAt: "2025-09-03T09:15:00.000Z",
    updatedAt: "2025-09-03T09:15:00.000Z",
    stateName: "Maharashtra",
    districtName: "Pune",
    mandalName: "Shivaji Nagar",
    assignedToLabel: "Kisani Didi (2)",
    assignedCount: 1, // 1 specific kisani didi
  },
  "assigned-1": {
    id: "assigned-1",
    title: "Crop Disease Survey",
    description: "Conduct a survey on crop diseases in the region. Document findings and recommend treatment plans.",
    status: "assigned",
    assigneeUserType: "kd", // Kisani Didi (collective)
    assigneeId: "user-kd-1",
    assignedAt: "2025-09-03T12:00:00.000Z",
    dueDate: "2025-09-15T00:00:00.000Z",
    createdAt: "2025-09-01T08:00:00.000Z",
    updatedAt: "2025-09-03T12:00:00.000Z",
    stateName: "Karnataka",
    districtName: "Bangalore",
    mandalName: "Mandya",
    assignedToLabel: "Kisani Didi (8)",
    assignedCount: 3, // 3 kisani didis assigned
  },
  "assigned-2": {
    id: "assigned-2",
    title: "Water Management",
    description: "Implement water management techniques for irrigation. Install new drip irrigation systems and optimize water usage.",
    status: "assigned",
    assigneeUserType: "ioperator", // Individual Operator
    assigneeId: "user-op-1",
    assignedAt: "2025-09-04T08:30:00.000Z",
    dueDate: "2025-10-25T23:59:59.000Z",
    createdAt: "2025-09-02T10:00:00.000Z",
    updatedAt: "2025-09-04T08:30:00.000Z",
    stateName: "Maharashtra",
    districtName: "Pune",
    mandalName: "Shivaji Nagar",
    assignedToLabel: "Farm Operator (1)",
    assignedCount: 1, // 1 specific operator
  },
  "draft-4": {
    id: "draft-4",
    title: "Irrigation System Setup",
    description: "Plan and set up new irrigation systems for the northern fields. Include drip irrigation and sprinkler systems.",
    status: "draft",
    assigneeUserType: "ioperator",
    assigneeId: "user-4",
    assignedAt: null,
    dueDate: "2025-09-30T00:00:00.000Z",
    createdAt: "2025-09-04T16:30:00.000Z",
    updatedAt: "2025-09-04T16:30:00.000Z",
    stateName: "Karnataka",
    districtName: "Bangalore",
    mandalName: "Mandya",
    assignedToLabel: "Farm Operator (1)",
    assignedCount: 1,
  },
  "draft-5": {
    id: "draft-5", 
    title: "Fertilizer Distribution Plan",
    description: "Create distribution plan for organic fertilizers across all registered farms in the region.",
    status: "draft",
    assigneeUserType: "ikd",
    assigneeId: "user-5",
    assignedAt: null,
    dueDate: "2025-10-05T00:00:00.000Z",
    createdAt: "2025-09-05T11:45:00.000Z",
    updatedAt: "2025-09-05T11:45:00.000Z",
    stateName: "Maharashtra",
    districtName: "Pune", 
    mandalName: "Shivaji Nagar",
    assignedToLabel: "Kisani Didi (2)",
    assignedCount: 1,
  },
  "assigned-3": {
    id: "assigned-3",
    title: "Harvest Planning",
    description: "Plan harvest schedule for wheat and rice crops. Coordinate with local farmers and arrange transportation.",
    status: "assigned",
    assigneeUserType: "fm",
    assigneeId: "user-fm-2",
    assignedAt: "2025-09-05T14:15:00.000Z",
    dueDate: "2025-11-30T23:59:59.000Z",
    createdAt: "2025-09-03T12:00:00.000Z",
    updatedAt: "2025-09-05T14:15:00.000Z",
    stateName: "Karnataka",
    districtName: "Bangalore",
    mandalName: "Mandya",
    assignedToLabel: "Farm Manager (5)",
    assignedCount: 4,
  },
  "assigned-4": {
    id: "assigned-4",
    title: "Seed Quality Check",
    description: "Conduct quality checks on all seed varieties before distribution. Test germination rates and purity.",
    status: "assigned",
    assigneeUserType: "ifm",
    assigneeId: "user-ifm-1",
    assignedAt: "2025-09-06T09:00:00.000Z",
    dueDate: "2025-09-18T00:00:00.000Z",
    createdAt: "2025-09-04T08:30:00.000Z",
    updatedAt: "2025-09-06T09:00:00.000Z",
    stateName: "Maharashtra",
    districtName: "Pune",
    mandalName: "Shivaji Nagar",
    assignedToLabel: "Farm Manager (3)",
    assignedCount: 1,
  },
};
